version: "3"
services:
  #  nginx:
  #  build: requirements/NGINX/
  #  container_name: NGINX
  #  restart: always
  #  ports:
  #    - "80:80"
  #    - "443:443"
  #  volumes:
  #    - server:/var/www/html/
  #  networks:
  #    - front
  #  depends_on:
  #    - "wordpress"
  #  logging:
  #    options:
  #      max-size: "10m"
  #      max-file: "3"

  #  wordpress:
  #  build: requirements/WordPress/
  #  container_name: WordPress
  #  env_file:
  #    - .env
  #  ports:
  #    - "9000:9000"
  #  volumes:
  #    - server:/var/www/html
  #  networks:
  #    - front
  #    - back
  #  depends_on:
  #    - "mariadb"
  #  restart: always
  #  logging:
  #    options:
  #      max-size: "10m"
  #      max-file: "3"

  mariadb:
    build: 
      context: requirements/MariaDB/
  # restart: always
      args:
        MYSQL_ADMIN_USER: ${MYSQL_ADMIN_USER}
        MYSQL_ADMIN_PASSWORD: ${MYSQL_ADMIN_PASSWORD}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        DB_NAME: ${DB_NAME}
    container_name: MariaDB
    ports:
      - "3306:3306"
    volumes:
      - sql:/var/lib/myswl/
    networks:
      - back
    logging:
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  server:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/tomartin/Inception/data/webserver'
  sql:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/tomartin/Inception/data/mysql'

networks:
  front:
  back:
