version: "3"
services:
  nginx:
    build: requirements/NGINX/
    container_name: NGINX
    restart: always
    depends_on:
      - "wordpress"
    ports:
      - "80:80"
      - "443:443"

  wordpress:
    build: requirements/WordPress/
    container_name: WordPress
    restart: always
    depends_on:
      - "mariadb"

  mariadb:
    build: requirements/MariaDB/
    container_name: MariaDB
    restart: always
    env_file:
      - .env
