version: "3"
services:

  nginx:
    container_name: NGINX
    restart: always
    build: requirements/NGINX/
    ports:
      - "443:443"
    volumes:
      - server:/var/www/html/
    networks:
      - front
    depends_on:
      - "wordpress"
    logging:
      options:
        max-size: "10m"
        max-file: "3"
  
  wordpress:
    container_name: WordPress
    restart: always
    build:
      context: requirements/WordPress/
      args:
        MYSQL_ADMIN_USER: ${MYSQL_ADMIN_USER}
        MYSQL_ADMIN_PASSWORD: ${MYSQL_ADMIN_PASSWORD}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        DB_NAME: ${DB_NAME}
        DB_HOST: ${DB_HOST}
    ports:
      - "9000:9000"
    volumes:
      - server:/var/www/html
    networks:
      - front
      - back
    depends_on:
      - "mariadb"
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  mariadb:
    container_name: MariaDB
    restart: always
    build: 
      context: requirements/MariaDB/
      args:
        MYSQL_ADMIN_USER: ${MYSQL_ADMIN_USER}
        MYSQL_ADMIN_PASSWORD: ${MYSQL_ADMIN_PASSWORD}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        DB_NAME: ${DB_NAME}
        DB_HOST: ${DB_HOST}
    ports:
      - "3306:3306"
    volumes:
      - sql:/var/lib/mysql/
    networks:
      - back
    logging:
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  server:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: "${HOME}/data/"
  sql:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: "${HOME}/data/mysql/"

networks:
  front:
  back:
